version: '3'

services:
  # Ingress service
  ingress:
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-assets/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker-assets/nginx/ssl/:/etc/nginx/ssl/

  database:
    image: mariadb:10.5
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - 'lobsters_database:/var/lib/mysql'

  forums:
    image: varange/lobsters:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database

  wordpress:
    image: wordpress:5-php7.2-fpm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - database

networks:
  default:
    external:
      name: lobsters-net

volumes:
  lobsters_database:
  wordpress:
