version: '3'

services:
  # Ingress service
  ingress:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-assets/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker-assets/nginx/ssl/:/etc/nginx/ssl/

  database:
    image: mariadb
    env_file:
      - .env
    volumes:
      - 'lobsters_database:/var/lib/mysql'
  app:
    image: varange/lobsters:latest
    env_file:
      - .env
    depends_on:
      - database

networks:
  default:
    external:
      name: lobsters-net

volumes:
  lobsters_database:
