version: '3'

services:
  # Ingress service
  ingress:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-assets/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker-assets/nginx/ssl/:/etc/nginx/ssl/

  database:
    image: mariadb
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lobsters_development
    volumes:
      - 'lobsters_database:/var/lib/mysql'
  app:
    image: varange/lobsters:latest
    build:
      context: .
      args:
        DEVELOPER_BUILD: "false"
    env_file:
      - .env
    environment:
      - MARIADB_HOST=database
      - MARIADB_PORT=3306
      - MARIADB_PASSWORD=password
      - MARIADB_USER=root
      - LOBSTER_DATABASE=lobsters
      - LOBSTER_SITE_NAME="Example News"
      - RAILS_ENV=development
      - LOBSTER_HOSTNAME=localhost
      - VIRTUAL_HOST=localhost
      - RAILS_MAX_THREADS=5

networks:
  default:
    external:
      name: lobsters-net

volumes:
  lobsters_database: